/**
 * REGRAS DO MÓDULO 3 — PLANO DE TRATAMENTO
 * Este arquivo contém as regras de combinação para atualizar a timeline e o resumo.
 * As chaves (key) devem estar em ordem alfabética, separadas por ponto e vírgula (;).
 */
window.M3_RULES = [
  {
    key: "DEFAULT",
    card1_title: "Selecione opções para realizar a simulação",
    card1_text: "",
    card2_title: "",
    card2_text: "",
    card3_title: "",
    card3_text: "",
    card4_title: "",
    card4_text: "",
    card5_title: "",
    card5_text: "",
    summary_text: "",
    sessionsnumber_text: "-",
    frequency_text: "x por semana"
  },
  {
    key: "Massagens",
    card1_title: "Massagem",
    card1_text: "",
    card2_title: "Massagem",
    card2_text: "",
    card3_title: "Massagem",
    card3_text: "",
    card4_title: "Massagem",
    card4_text: "",
    card5_title: "Massagem",
    card5_text: "",
    summary_text: "Plano focado em modelagem e harmonizar o corpo em conjunto de uma drenagem e melhora da circulação.",
    sessionsnumber_text: "5 a 10 sessões",
    frequency_text: "1x a 2x por semana"
  },
  {
    key: "Enzimas;Ultrassom",
    card1_title: "Enzimas",
    card1_text: "Aplicação de enzimas isoladamente.",
    card2_title: "Ultrassom",
    card2_text: "Sessão de Ultrassom isoladamente.",
    card3_title: "Enzimas e Ultrassom",
    card3_text: "Aplicação mista com o uso do ultrassom e enzimas.",
    card4_title: "Enzimas e Ultrassom",
    card4_text: "Aplicação mista com o uso do ultrassom e enzimas.",
    card5_title: "Enzimas e Ultrassom",
    card5_text: "Aplicação mista com o uso do ultrassom e enzimas.",
    summary_text: "Plano sinérgico combinando quebra química e mecânica para um ótimo resultado.",
    sessionsnumber_text: "5 sessões",
    frequency_text: "1x por semana"
  },
  {
    key: "Estímulo Metabólico",
    card1_title: "Aplicação de Injeção Metabólica",
    card1_text: "",
    card2_title: "",
    card2_text: "",
    card3_title: "",
    card3_text: "",
    card4_title: "",
    card4_text: "",
    card5_title: "",
    card5_text: "",
    summary_text: "Plano focado em acelerar o metabolismo e potencializar a queima de calóricas.",
    sessionsnumber_text: "1 sessão",
    frequency_text: "1x por trimestre"
  },
  {
    key: "Hidrolipo;Ultrassom",
    card1_title: "Avaliação Combinada",
    card1_text: "Mapeamento para infiltração e ajuste de potência do US.",
    card2_title: "Infiltração",
    card2_text: "Aplicação de solução para potencializar o ultrassom.",
    card3_title: "Sessão Híbrida",
    card3_text: "Combinação de hidrolipoclasia e ultrassom cavitacional.",
    card4_title: "Eliminação",
    card4_text: "Processo intenso de eliminação de lipídios.",
    card5_title: "Consolidação",
    card5_text: "Reavaliação da redução de medidas e ajuste de plano.",
    summary_text: "Plano focado em redução localizada com hidrolipo e ultrassom. Reavaliação inclusa para cumprimento do objetivo.",
    sessionsnumber_text: "5 sessões",
    frequency_text: "1x por semana"
  },
  {
    key: "Estímulo Metabólico;Hidrolipo;Ultrassom",
    card1_title: "Avaliação Avançada",
    card1_text: "Mapeamento completo incluindo perfil metabólico.",
    card2_title: "Preparação",
    card2_text: "Infiltração e ativação metabólica prévia.",
    card3_title: "Tripla Ação",
    card3_text: "Hidrolipo + Ultrassom + Estímulo Metabólico.",
    card4_title: "Metabolização",
    card4_text: "Aceleração da queima da gordura liberada.",
    card5_title: "Resultado",
    card5_text: "Acompanhamento intensivo dos resultados.",
    summary_text: "Plano completo combinando redução mecânica e aceleração metabólica.",
    sessionsnumber_text: "8 sessões",
    frequency_text: "1x por semana"
  },
  {
    key: "Enzimas;Estímulo Metabólico;Ultrassom",
    card1_title: "Avaliação Sistêmica",
    card1_text: "Análise de enzimas e suporte metabólico.",
    card2_title: "Preparação",
    card2_text: "Assepsia e ativação térmica.",
    card3_title: "Ação Potencializada",
    card3_text: "Enzimas + Ultrassom com metabolismo ativo.",
    card4_title: "Drenagem",
    card4_text: "Estímulo para eliminação rápida de ativos.",
    card5_title: "Manutenção",
    card5_text: "Foco em manter o metabolismo elevado.",
    summary_text: "Plano de alta performance para quebra química e mecânica com suporte metabólico.",
    sessionsnumber_text: "10 sessões",
    frequency_text: "1x por semana"
  },
  {
    key: "Enzimas;Estímulo Metabólico;Hidrolipo;Ultrassom",
    card1_title: "Protocolo Full",
    card1_text: "Mapeamento total de todas as frentes de tratamento.",
    card2_title: "Preparação",
    card2_text: "Infiltração e ativação sistêmica.",
    card3_title: "Sessão Master",
    card3_text: "Combinação de todas as tecnologias disponíveis.",
    card4_title: "Recuperação",
    card4_text: "Monitoramento pós-procedimento completo.",
    card5_title: "Consolidação",
    card5_text: "Plano de longo prazo para manutenção.",
    summary_text: "O protocolo mais completo para redução de medidas e melhora metabólica.",
    sessionsnumber_text: "12 sessões",
    frequency_text: "1x por semana"
  },
  {
    key: "Enzimas;Hidrolipo;Ultrassom",
    card1_title: "Avaliação de Lise",
    card1_text: "Foco em quebra química e mecânica profunda.",
    card2_title: "Infiltração",
    card2_text: "Preparação do tecido com solução e enzimas.",
    card3_title: "Lise Adiposa",
    card3_text: "Ação conjunta para destruição de adipócitos.",
    card4_title: "Eliminação",
    card4_text: "Foco em vias de excreção de gordura.",
    card5_title: "Revisão",
    card5_text: "Ajuste de pontos para próxima sessão.",
    summary_text: "Plano intensivo de redução sem foco metabólico inicial.",
    sessionsnumber_text: "6 sessões",
    frequency_text: "1x por semana"
  },
  {
    key: "Massagens;Ultrassom",
    card1_title: "Avaliação de Contorno",
    card1_text: "Análise da gordura localizada e tônus muscular.",
    card2_title: "Preparação",
    card2_text: "Aplicação de gel condutor e ativos lipolíticos.",
    card3_title: "Sessão Integrada",
    card3_text: "Ultrassom cavitacional seguido de massagem modeladora.",
    card4_title: "Drenagem Ativa",
    card4_text: "Manobras para acelerar a eliminação da gordura mobilizada.",
    card5_title: "Finalização",
    card5_text: "Aplicação de gel crioterápico para firmar a pele.",
    summary_text: "Plano focado em redução de medidas e modelagem corporal intensa.",
    sessionsnumber_text: "8 sessões",
    frequency_text: "2x por semana"
  },
  {
    key: "Ultrassom",
    card1_title: "Consulta Avaliativa",
    card1_text: "Análise da gordura localizada e tônus muscular.",
    card2_title: "Ultrassom",
    card2_text: "INSERIR INFORMAÇÃO.",
    card3_title: "Ultrassom",
    card3_text: "INSERIR INFORMAÇÃO.",
    card4_title: "Ultrassom",
    card4_text: "INSERIR INFORMAÇÃO.",
    card5_title: "Ultrassom",
    card5_text: "INSERIR INFORMAÇÃO.",
    summary_text: "Plano focado na quebra mecânica do tecido adiposo para um ótimo resultado.",
    sessionsnumber_text: "4 sessões",
    frequency_text: "1x por semana"
  }
];



